### ISSUE TITLE
Add injection of custom package sources

### ISSUE THREAD

**Issue by PathogenDavid** [NgrDavid/setup-bonsai#3]
```yml
inject-sources:
  description: 'A list of extra package sources to inject to the NuGet.config.'
```

Your first instinct may be to tell people to just populate a `NuGet.config` directly from their CI, IE:

```
- name: Add extra package feeds for CI
  run: cp .github/workflows/ExtraNuGet.config ../NuGet.config
```

However this is error-prone for a multitude of reasons.

It doesn't work well with multiple Bonsai environments. For example, if you want to inject feeds into your root `.bonsai` environment but not `docs/examples/CoolExample/.bonsai` you'd have to add an extra protective `NuGet.config` to `docs/NuGet.config` to remove the sources or something like that.

You could instead overwrite `.bonsai/NuGet.config`, but then you'd have to make sure that anything added to the real `NuGet.config` is also added to the `ExtraNuGet.config` which feels error-prone.

Additionally the fact that you can/should use `../NuGet.config` (as in the example above) to avoid issues with blowing away a `NuGet.config` in the repo root is non-obvious.

Additionally++, if people get tempted to put the `NuGet.config` in a [Actions variable](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables), it's actually fairly error-prone to write out a multi-line variable to a file. (`printf "%s" "$EXTRA_NUGET_CONFIG" > NuGet.config` is the right solution...[probably](https://stackoverflow.com/questions/11618696/shell-write-variable-contents-to-a-file/) 😵)

Finally, both of these solutions are a bit sketchy if any of your sources require authentication as you would ideally need to [tell GitHub it's a secret](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#masking-a-value-in-a-log) so it gets censored if it were to end up in a log. You also ideally don't want it in an Actions variable but instead an Actions secret, but putting the whole NuGet.config in a secret is annoying and doing interpolation to combine a separate NuGet.config template variable and password secret is a pain.

For similar reasons you'd also want to make sure your `<packageSourceCredentials>` lives somewhere outside of the repo file tree to hopefully avoid it ending up in some artifact (particularly rarely-published/inspected artifacts like ones used for debugging.

--------------------

Need to determine how to best pass the configuration. Action parameters unfortunately don't allow passing full YAML objects, which unfortunately means what I'd prefer is not possible:

```yml
- name: Setup Bonsai Environments
  uses: bonsai-rx/setup-bonsai@v1
  with:
    inject-sources:
      - source: Mochi Libraries CI
        url: https://nuget-ci.mochilibraries.net/index.json
        username: ${{vars.MOCHILIBRARIES_FEED_USERNAME}}
        password: ${{secrets.MOCHILIBRARIES_FEED_PASSWORD}}
```

Most likely we'd need to use a multi-line string. Maybe encoded as INI so it doesn't get lost in the sauce?

```yml
steps:
- name: Setup Bonsai Environments
  uses: bonsai-rx/setup-bonsai@v1
  with:
    inject-sources: |
      [Mochi Libraries CI]
      url = https://nuget-ci.mochilibraries.net/index.json
      username = ${{vars.MOCHILIBRARIES_FEED_USERNAME}}
      password = ${{secrets.MOCHILIBRARIES_FEED_PASSWORD}}
```
